name: clientes_pago_app
description: App simple para mostrar clientes con pago hoy (generado automáticamente)
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_local_notifications: any

flutter:
  uses-material-design: true